baseurl = "https://rhasanm.github.io/being-data-engineer"
title = "Being Data Engineer"
languageCode = "en-us"

theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  description = "Journey to become a data engineer..."